### ISSUE TITLE
Issue with las file while importing

### ISSUE THREAD

**Issue by passenger3e** [imranfadhil/logASCII_viewer#2]
Hello,
I tried some las files even found on the internet( Las 2.0) no luck i am getting some errors: AttributeError 'DataFrame' object has no attribute 'append'
Traceback Lines: 
script_runner.py line 589
app.py Line 10
LAS_handler.py Line 43
generic.py Line 6299.
Can you upload some working las file examples.
Thank you.

**Comment by imranfadhil** [comment]
Hi passenger3e, the code was obsolete.

I've updated the code, readme and added requirements.txt (tested with Python 3.10).
Should be working for generic LAS files.

Regards.

**Comment by passenger3e** [comment]
Hi imranfadhil,
It is working now. thank you for the update.
Regards.
